'''
This test file needs the following files:
STR_SUMO.py, RouteController.py, Util.py, test.net.xml, test.rou.xml, myconfig.sumocfg and corresponding SUMO libraries.
'''
from core.STR_SUMO import StrSumo
import os
import sys
from xml.dom.minidom import parse, parseString
from core.Util import *
from controller.RouteController import *
from controller.DijkstraController import DijkstraPolicy
from controller.QLearningController import QLearningPolicy
from core.target_vehicles_generation_protocols import *
import copy

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("No environment variable SUMO_HOME!")

from sumolib import checkBinary
import traci


# use vehicle generation protocols to generate vehicle list
def get_controlled_vehicles(route_filename, connection_info, \
    num_controlled_vehicles=20, num_uncontrolled_vehicles=30, pattern = 3):
    '''
    :param @route_filename <str>: the name of the route file to generate
    :param @connection_info <object>: an object that includes the map inforamtion
    :param @num_controlled_vehicles <int>: the number of vehicles controlled by the route controller
    :param @num_uncontrolled_vehicles <int>: the number of vehicles not controlled by the route controller
    :param @pattern <int>: one of four possible patterns. FORMAT:
            -- CASES BEGIN --
                #1. one start point, one destination for all target vehicles
                #2. ranged start point, one destination for all target vehicles
                #3. ranged start points, ranged destination for all target vehicles
            -- CASES ENDS --
    '''
    vehicle_dict = {}
    print(connection_info.net_filename)
    generator = target_vehicles_generator(connection_info.net_filename)

    # list of target vehicles is returned by generate_vehicles
    vehicle_list = generator.generate_vehicles(num_controlled_vehicles, num_uncontrolled_vehicles, \
        pattern, route_filename, connection_info.net_filename)

    for vehicle in vehicle_list:
        vehicle_dict[str(vehicle.vehicle_id)] = vehicle

    return vehicle_dict

def test_dijkstra_policy(vehicles):
    print("Testing Dijkstra's Algorithm Route Controller")
    scheduler = DijkstraPolicy(init_connection_info)
    run_simulation(scheduler, vehicles)

def test_q_learning(vehicles):
    print("Testing Q Learning Route Controller")
    scheduler = QLearningPolicy(vehicles, init_connection_info, './configurations/rl_model_test.h5') # Please watch for the correct rl_model.h5 file generated by train_rl.py
    run_simulation(scheduler, vehicles)

def run_simulation(scheduler, vehicles):

    simulation = StrSumo(scheduler, init_connection_info, vehicles)

    """
    The traci start below use sumocfg files from configurations, which match with the one you use in train_rl.py. If you change in either place, you need to change in the other one too.

    Output from main.py will be located in main_output to avoid confusion with the output generated by train_rl.py which located in configurations
    """
    traci.start([sumo_binary, "-c", "./configurations/myconfig.sumocfg", \
                 "--tripinfo-output", "./main_output/trips.trips.xml", \
                 "--fcd-output", "./main_output/testTrace.xml","--quit-on-end"]) #The sumocfg file need to match with the one used in train_rl.py
    try:
        total_time, end_number, deadlines_missed = simulation.run()
        print("Average timespan: {}, total vehicle number: {}, total vehicles reached destination: {}".format(str(total_time/end_number),\
            str(len(vehicles)), str(end_number)))
        print(str(deadlines_missed) + ' deadlines missed.')
    finally:
        if traci.isLoaded():
            traci.close()

if __name__ == "__main__":
    sumo_binary = checkBinary('sumo-gui')
    # sumo_binary = checkBinary('sumo')#use this line if you do not want the UI of SUMO

    # parse config file for map file name
    dom = parse("./configurations/myconfig.sumocfg")

    net_file_node = dom.getElementsByTagName('net-file')
    net_file_attr = net_file_node[0].attributes

    net_file = net_file_attr['value'].nodeValue
    init_connection_info = ConnectionInfo("./configurations/"+net_file)

    route_file_node = dom.getElementsByTagName('route-files')
    route_file_attr = route_file_node[0].attributes
    route_file = "./configurations/"+route_file_attr['value'].nodeValue
    vehicles = get_controlled_vehicles(route_file, init_connection_info, 8, 15)
    #print the controlled vehicles generated
    for vid, v in vehicles.items():
        print("id: {}, destination: {}, start time:{}, deadline: {};".format(vid, \
            v.destination, v.start_time, v.deadline))
    # test_dijkstra_policy(copy.deepcopy(vehicles))
    test_q_learning(copy.deepcopy(vehicles))
